<?php

namespace App\Models;

/**
 * Class NotificationType
 * @package App\Models
 * @version March 10, 2020, 4:26 pm UTC
 *
 * @property integer resource_type_id
 * @property integer creator_id
 * @property string name
 * @property string description
 * @property string status
 */
class NotificationType extends Model
{

    public $table = 'notifications_types';
    
    const STATUS_PUBLISHED = 1 ;
    const OTP_INVITE = 'OTP_INVITE' ;
    const CREATE_CONTRIBUTOR = 'CREATE_CONTRIBUTOR' ;
    const ATTENDEES_INVITATION = 'ATTENDEES_INVITATION' ;
    const MEETING_UPDATES = 'MEETING_UPDATES' ;
    const MEETING_CANCEL = 'MEETING_CANCEL' ;
    const MEETING_PUBLISH = 'MEETING_PUBLISH' ;
    const ASSOCIATION_MEETING_PUBLISH = 'ASSOCIATION_MEETING_PUBLISH' ;
    const MEETING_FINISH = 'MEETING_FINISH' ;
    const TIME_VOTING_INVITATION = 'TIME_VOTING_INVITATION' ;
    const CLOSE_VOTING = 'CLOSE_VOTING';
    const DELEGATE_INVITATION_CANCELED = 'DELEGATE_INVITATION_CANCELED' ;
    const NOTIFY_SECRETARY_WITH_NEW_COMMENT = 'NOTIFY_SECRETARY_WITH_NEW_COMMENT' ;
    const NOTIFY_ATTENDEES_WITH_ATTENDENCE_STATUS_UPDATE = 'NOTIFY_ATTENDEES_WITH_ATTENDENCE_STATUS_UPDATE' ;
    const NOTIFY_COMMENT_REPLY = 'NOTIFY_COMMENT_REPLY' ;
    const NOTIFY_REMINDER = 'NOTIFY_REMINDER' ;
    const ACTION_VOTING_NOTIFICATION = 'ACTION_VOTING_NOTIFICATION' ;
    const ACTION_DELEGATE_VOTING_NOTIFICATION = 'ACTION_DELEGATE_VOTING_NOTIFICATION' ;
    const ACTION_DELEGATE_VOTING_REJECTED_NOTIFICATION = 'ACTION_DELEGATE_VOTING_REJECTED_NOTIFICATION' ;
    const ATTENDEES_UPDATE_ACTION = 'ATTENDEES_UPDATE_ACTION' ;
    const ATTENDEES_PUBLISH_ACTION = 'ATTENDEES_PUBLISH_ACTION' ;
    const ATTENDEES_CANCEL_ACTION = 'ATTENDEES_CANCEL_ACTION' ;
    const ATTENDEES_END_ACTION = 'ATTENDEES_END_ACTION' ;
    const ATTENDEES_NEW_ACTION = 'ATTENDEES_NEW_ACTION' ;
    const ASSIGNEE_UPDATE_ACTION = 'ASSIGNEE_UPDATE_ACTION' ;
    const ASSIGNEE_PUBLISH_ACTION = 'ASSIGNEE_PUBLISH_ACTION' ;
    const ASSIGNEE_CANCEL_ACTION = 'ASSIGNEE_CANCEL_ACTION' ;
    const ASSIGNEE_END_ACTION = 'ASSIGNEE_END_ACTION' ;
    const START_MEETING_NOTIFICATION = 'START_MEETING_NOTIFICATION';
    const MEETING_REPORT_FINISH = 'MEETING_REPORT_FINISH';
    const Add_Notice_To_MEETING_REPORT = 'Add_Notice_To_MEETING_REPORT';
    const MEETING_REPORT_NOTIFY_SIGN = 'MEETING_REPORT_NOTIFY_SIGN';
    const MEETING_REPORT_SHARE = 'MEETING_REPORT_SHARE';
    CONST MEETING_COLLECTION_PUBLISH = 'MEETING_COLLECTION_PUBLISH';
    CONST ANNOTATION_PUBLISH = 'ANNOTATION_PUBLISH';
    CONST NOTIFY_SHARE_WITH_NEW_COMMENT = 'NOTIFY_SHARE_WITH_NEW_COMMENT';
    CONST NOTIFY_MENSIONS_NEW_COMMENT = 'NOTIFY_MENSIONS_NEW_COMMENT';
    CONST MEETING_NOTICE_APPROVE = 'MEETING_NOTICE_APPROVE';
    CONST MEETING_REPORT_NOTIFY_SIGN_TO_SECRETARY = 'MEETING_REPORT_NOTIFY_SIGN_TO_SECRETARY';
    CONST ASSIGNEE_NEW_ACTION = 'ASSIGNEE_NEW_ACTION';
    CONST ASSIGNEE_NEW_TASK = 'ASSIGNEE_NEW_TASK';
    CONST ACTION_DUE_DATE_NOTIFICATION  = 'ACTION_DUE_DATE_NOTIFICATION';
    CONST TASK_DUE_DATE_NOTIFICATION  = 'TASK_DUE_DATE_NOTIFICATION';
    CONST TASK_FINISHED_NOTIFICATION   = 'TASK_FINISHED_NOTIFICATION';
    CONST DIRECTORY_SHARE_INITATION = 'DIRECTORY_SHARE_INITATION';
    CONST MEDIA_SHARE_INITATION = 'MEDIA_SHARE_INITATION';
    CONST FINISH_MEMBERSHIP_NOTIFICATION = 'FINISH_MEMBERSHIP_NOTIFICATION';
    CONST MEETING_ABSENCE_REGULATION = 'MEETING_ABSENCE_REGULATION';
    CONST VOTE_MEETING_TIMES = 'VOTE_MEETING_TIMES';
    CONST VOTE_MEETING_ACTION = 'VOTE_MEETING_ACTION';
    CONST BOARD_CREATE = 'BOARD_CREATE';
    CONST BOARD_UPDATE = 'BOARD_UPDATE';
    CONST MEETING_MINUTES_PUBLISHED = 'MEETING_MINUTES_PUBLISHED';
    CONST NOTIFY_SECRETARY_WHEN_MEMBER_PUT_ANNOTATION_ON_MEETING_MINUTES = 'NOTIFY_SECRETARY_WHEN_MEMBER_PUT_ANNOTATION_ON_MEETING_MINUTES';
    CONST NOTIFY_SECRETARY_WHEN_MEMBER_APPROVED_ON_MEETING_MINUTES = 'NOTIFY_SECRETARY_WHEN_MEMBER_APPROVED_ON_MEETING_MINUTES'  ;
    CONST NOTIFY_MEMBER_WHEN_MEETING_CIRCULATED_FOR_SIGNTATURE = 'NOTIFY_MEMBER_WHEN_MEETING_CIRCULATED_FOR_SIGNTATURE';
    CONST NOTIFY_SECRETARY_WHEN_MEMBER_PUT_SIGNTATURE = 'NOTIFY_SECRETARY_WHEN_MEMBER_PUT_SIGNTATURE';
    CONST NOTIFY_MEMBER_WHEN_MEETING_MINUTES_OFFICIALLY_PUBLISHED = 'NOTIFY_MEMBER_WHEN_MEETING_MINUTES_OFFICIALLY_PUBLISHED';
    CONST NOTIFY_DEISION_OWNER_TASK_OWNER_MENTIONED_HIM_IN_COMMENT = 'NOTIFY_DEISION_OWNER_TASK_OWNER_MENTIONED_HIM_IN_COMMENT';
    CONST NOTIFY_MEMBER_WHEN_NEW_REOLUTION_CIRCULATED = 'NOTIFY_MEMBER_WHEN_NEW_REOLUTION_CIRCULATED' ;
    CONST NOTIFY_SECRETARY_WHEN_EVERYTIME_MEMBER_VOTED = 'NOTIFY_SECRETARY_WHEN_EVERYTIME_MEMBER_VOTED';
    CONST NOTIFY_MEMBER_WHEN_NEW_REOLUTION_MODIFIED = 'NOTIFY_MEMBER_WHEN_NEW_REOLUTION_MODIFIED';
    CONST NOTIFY_MEMBER_WHEN_NEW_REOLUTION_CANCELLED = 'NOTIFY_MEMBER_WHEN_NEW_REOLUTION_CANCELLED';
    CONST NOTIFY_MEMBER_WHEN_NEW_REOLUTION_ENDED = 'NOTIFY_MEMBER_WHEN_NEW_REOLUTION_ENDED';
    CONST NOTIFY_SECRETARY_WITH_THE_END_REOLUTION_RESULTS = 'NOTIFY_SECRETARY_WITH_THE_END_REOLUTION_RESULTS';
    CONST NOTIFY_MEMBER_WHEN_SECRETARY_SHARE_FILE_WITH_HIM = 'NOTIFY_MEMBER_WHEN_SECRETARY_SHARE_FILE_WITH_HIM';
    const ACTIVATE_USER = 'ACTIVATE_USER' ;
    const ACCOUNT_ACTIVATION = 'ACCOUNT_ACTIVATION' ;
    const FORGET_PASSWORD = 'FORGET_PASSWORD' ;
    const USER_INVITATION = 'USER_INVITATION' ;
    const UPDATE_COMMENT = 'UPDATE_COMMENT' ;
    const DELETE_COMMENT = 'DELETE_COMMENT' ;
    const UPDATE_COMMENT_REPLY = 'UPDATE_COMMENT_REPLY' ;
    const DELETE_COMMENT_REPLY = 'DELETE_COMMENT_REPLY' ;
    const SEND_VOTING_CARD = 'SEND_VOTING_CARD' ;


    

    public $fillable = [
        'id',
        'code',
        'creator_id',
        'language_id',
        'translation_id',
        'name',
        'description',
        'status'
    ];

    
}
